### ISSUE TITLE
changeFilmback.changeFilmback_UI 이름 단순화

### ISSUE THREAD

**Issue by kybin** [coldmine/changeFilmback#2]
changeFilmback.changeFilmback_UI라는 이름은 중복 같아 보여요.
changeFilmback.UI로 이름을 바꾸면 어떨까요?

**Comment by kohyuk91** [comment]
오오 단순화 시켜 볼게요 ㅋ

**Comment by kybin** [comment]
e98437fce58c7db87a734879ed23431cf530ff1c 에 의해 해결됨.
